export const colors = {
  colorLight: `#f5f5f5`,
  colorLighter: `#fdfdfd`,
  colorDark: `#444444`,
  colorDarker: `#333333`,
  colorGrey: `#777777`,
  colorGreyer: `#999999`,
  colorGreyLess: `#dddddd`,
  colorPrimary: `#f5668c`,
  colorPrimaryLess: `#ff90ad`,
  colorPrimaryMore: `#fd3b6f`,
  colorSecondary: `#98c4ef`,
  colorSecondaryLess: `#b0d8ff`,
  colorSecondaryMore: `#3997f5`,
  colorTertiary: `#baea93`,
  colorTertiaryLess: `#ccf7a9`,
  colorTertiaryMore: `#8aeb3c`,
  colorQuaternary: `#ffaa65`,
  colorQuaternaryLess: `#fdc393`,
  colorQuaternaryMore: `#ff9c4a`,
};
